name: Create Tag and Release on Push

on:
  push:
    branches:
      - master

jobs:
  create-release:
    name: Create Tag and Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Get Current Tag
      id: get_current_tag
      run: |
        latest_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")
        echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

    - name: Increment Version
      id: increment_version
      run: |
        # Get the latest tag
        IFS='.' read -r major minor patch <<< "${LATEST_TAG/v/}"
        patch=$((patch+1))
        new_tag="v${major}.${minor}.${patch}"
        echo "NEW_TAG=$new_tag" >> $GITHUB_ENV
        echo "New version: $new_tag"

    - name: Create Tag
      id: create_tag
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag $NEW_TAG
        git push origin $NEW_TAG

    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.NEW_TAG }}
        release_name: Release ${{ env.NEW_TAG }}
        body: "Automated release generated by GitHub Actions."
        draft: false
        prerelease: false
